import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const PLANS = [
  { name: 'Tier 1', monthlyPrice: '25.00', sortOrder: 1 },
  { name: 'Tier 2', monthlyPrice: '45.00', sortOrder: 2 },
  { name: 'Tier 3', monthlyPrice: '70.00', sortOrder: 3 },
];

// Deliberate one-time duplication of landing/public/js/materials-data.js's
// MATERIALS array — see the "Seed data" section of
// docs/superpowers/specs/2026-09-11-material-selector-library-design.md.
// `landing/` and `platform/api` are separate apps with separate databases
// and no shared import boundary, so there is no way to share the literal
// source without new cross-app plumbing that isn't otherwise needed. If the
// two ever drift, that's expected; this table is the source of truth for
// the in-app tenant-facing feature, materials-data.js for the public page.
const MATERIALS = [
  {
    id: 'pla',
    name: 'PLA',
    chemistry: 'Polylactic acid',
    bestFor: 'Display models, prototypes and light indoor parts',
    nozzleTempC: 200,
    bedTempC: 60,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: false,
    recommendsVentilation: false,
    difficulty: 'Beginner',
    moisture: 'Low',
    abrasive: false,
    priceZarPerKgLow: 295,
    priceZarPerKgHigh: 425,
    priceEstimated: false,
    whyChooseIt: 'Prints cleanly on almost any machine with no tuning.',
    avoidWhenText: 'The part will sit in a hot car, in direct sun, or carry sustained load — PLA softens well below 60°C and creeps under stress over time.',
    tags: ['beginner-friendly'],
  },
  {
    id: 'petg',
    name: 'PETG',
    chemistry: 'Glycol-modified PET',
    bestFor: 'Everyday functional parts, indoors or out of direct sun',
    nozzleTempC: 230,
    bedTempC: 70,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Beginner',
    moisture: 'Medium',
    abrasive: false,
    priceZarPerKgLow: 290,
    priceZarPerKgHigh: 450,
    priceEstimated: false,
    whyChooseIt: 'Strong, a little flexible, and noticeably tougher than PLA for a similar price.',
    avoidWhenText: 'You need crisp fine detail (PETG strings more than PLA) or real heat resistance.',
    tags: ['beginner-friendly'],
  },
  {
    id: 'abs',
    name: 'ABS',
    chemistry: 'Acrylonitrile butadiene styrene',
    bestFor: 'Enclosure parts, housings and heat-exposed indoor parts',
    nozzleTempC: 230,
    bedTempC: 90,
    requiresEnclosure: true,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: false,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'Low',
    abrasive: false,
    priceZarPerKgLow: 300,
    priceZarPerKgHigh: 450,
    priceEstimated: false,
    whyChooseIt: 'Good heat resistance (to roughly 100°C) and can be acetone-vapour-smoothed.',
    avoidWhenText: 'You print in a bedroom or unventilated space (styrene fumes) or your printer has no enclosure — ABS warps and delaminates badly without one.',
    tags: ['engineering'],
  },
  {
    id: 'peek',
    name: 'PEEK',
    chemistry: 'Polyether ether ketone',
    bestFor: 'Aerospace, medical and extreme-temperature parts',
    nozzleTempC: 360,
    bedTempC: 120,
    requiresEnclosure: true,
    requiresHardenedNozzle: true,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'Medium',
    abrasive: false,
    priceZarPerKgLow: 8000,
    priceZarPerKgHigh: 15000,
    priceEstimated: true,
    whyChooseIt: 'Metal-like strength and stiffness, holds up past 250°C, chemically near-inert.',
    avoidWhenText: 'You don’t have a genuine high-temperature industrial printer — most desktop machines simply cannot reach PEEK’s processing temperature at all.',
    tags: ['engineering', 'outdoor-safe'],
  },
  {
    id: 'pla-cf',
    name: 'PLA-CF',
    chemistry: 'PLA reinforced with chopped carbon fibre',
    bestFor: 'Rigid jigs, fixtures and low-warp tooling with a matte finish',
    nozzleTempC: 215,
    bedTempC: 60,
    requiresEnclosure: false,
    requiresHardenedNozzle: true,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Intermediate',
    moisture: 'Medium',
    abrasive: true,
    priceZarPerKgLow: 450,
    priceZarPerKgHigh: 650,
    priceEstimated: false,
    whyChooseIt: 'Noticeably stiffer and flatter-printing than standard PLA — great for jigs and fixtures that must hold a shape.',
    avoidWhenText: 'You need a smooth cosmetic surface or thin flexible walls — carbon fibre gives a matte, slightly grainy finish and chews through brass nozzles.',
    tags: ['engineering'],
  },
  {
    id: 'silk-pla',
    name: 'Silk PLA',
    chemistry: 'PLA blend with gloss-modifying additives',
    bestFor: 'Decorative display pieces, vases and gifts wanting a glossy sheen',
    nozzleTempC: 215,
    bedTempC: 60,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: false,
    recommendsVentilation: false,
    difficulty: 'Beginner',
    moisture: 'Low',
    abrasive: false,
    priceZarPerKgLow: 320,
    priceZarPerKgHigh: 480,
    priceEstimated: false,
    whyChooseIt: 'Gives a genuine glossy, silk-like sheen straight off the printer with no post-processing.',
    avoidWhenText: 'The part needs real strength or fine detail — silk PLA is more brittle and strings more than standard PLA.',
    tags: ['beginner-friendly'],
  },
  {
    id: 'matte-pla',
    name: 'Matte PLA',
    chemistry: 'PLA with mineral fillers for a matte surface',
    bestFor: 'Props and models where a glare-free, non-shiny surface matters',
    nozzleTempC: 210,
    bedTempC: 55,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: false,
    recommendsVentilation: false,
    difficulty: 'Beginner',
    moisture: 'Low',
    abrasive: false,
    priceZarPerKgLow: 320,
    priceZarPerKgHigh: 480,
    priceEstimated: false,
    whyChooseIt: 'Hides layer lines and kills glare, which makes it a favourite for photography props and painted models.',
    avoidWhenText: 'You need maximum layer adhesion strength — the matte fillers slightly reduce interlayer bonding versus standard PLA.',
    tags: ['beginner-friendly'],
  },
  {
    id: 'wood-pla',
    name: 'Wood PLA',
    chemistry: 'PLA blended with fine wood fibre',
    bestFor: 'Decorative pieces wanting a genuine wood look, smell and sandable finish',
    nozzleTempC: 200,
    bedTempC: 55,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Beginner',
    moisture: 'Medium',
    abrasive: true,
    priceZarPerKgLow: 350,
    priceZarPerKgHigh: 550,
    priceEstimated: false,
    whyChooseIt: 'Genuine wood fibre gives a sandable, stainable surface and a warm visual texture plain PLA can’t match.',
    avoidWhenText: 'The part needs fine detail or real mechanical strength — wood fibre weakens interlayer bonding and can clog small nozzles over time.',
    tags: ['beginner-friendly'],
  },
  {
    id: 'tough-pla',
    name: 'Tough PLA',
    chemistry: 'Impact-modified PLA copolymer',
    bestFor: 'Functional parts needing impact resistance without ABS-style warping',
    nozzleTempC: 215,
    bedTempC: 55,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: false,
    recommendsVentilation: false,
    difficulty: 'Beginner',
    moisture: 'Low',
    abrasive: false,
    priceZarPerKgLow: 320,
    priceZarPerKgHigh: 480,
    priceEstimated: false,
    whyChooseIt: 'Significantly higher impact strength than standard PLA while printing just as easily, with no enclosure needed.',
    avoidWhenText: 'You want PLA’s usual stiffness and crisp layer definition — Tough PLA trades some of both away for impact resistance.',
    tags: ['beginner-friendly'],
  },
  {
    id: 'petg-cf',
    name: 'PETG-CF',
    chemistry: 'PETG reinforced with chopped carbon fibre',
    bestFor: 'Rigid functional brackets and jigs needing PETG’s toughness plus stiffness',
    nozzleTempC: 255,
    bedTempC: 80,
    requiresEnclosure: false,
    requiresHardenedNozzle: true,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Intermediate',
    moisture: 'Medium',
    abrasive: true,
    priceZarPerKgLow: 480,
    priceZarPerKgHigh: 700,
    priceEstimated: false,
    whyChooseIt: 'Adds real stiffness and cuts warp versus standard PETG, holding sharper edges under load.',
    avoidWhenText: 'You need a smooth cosmetic finish or you’re printing through a standard brass nozzle — carbon fibre leaves a grainy surface and wears brass out fast.',
    tags: ['engineering'],
  },
  {
    id: 'asa',
    name: 'ASA',
    chemistry: 'Acrylonitrile styrene acrylate',
    bestFor: 'Outdoor brackets, enclosures and signage exposed to sun and weather',
    nozzleTempC: 250,
    bedTempC: 100,
    requiresEnclosure: true,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: false,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'Low',
    abrasive: false,
    priceZarPerKgLow: 350,
    priceZarPerKgHigh: 500,
    priceEstimated: false,
    whyChooseIt: 'Prints like ABS but with real UV and weather resistance for parts that live outdoors permanently.',
    avoidWhenText: 'You print in an unventilated room without an enclosure — ASA shares ABS’s warping and styrene-fume issues.',
    tags: ['outdoor-safe'],
  },
  {
    id: 'asa-cf',
    name: 'ASA-CF',
    chemistry: 'ASA reinforced with chopped carbon fibre',
    bestFor: 'Outdoor structural brackets needing stiffness plus UV resistance',
    nozzleTempC: 260,
    bedTempC: 100,
    requiresEnclosure: true,
    requiresHardenedNozzle: true,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'Medium',
    abrasive: true,
    priceZarPerKgLow: 600,
    priceZarPerKgHigh: 900,
    priceEstimated: true,
    whyChooseIt: 'Combines ASA’s weatherability with carbon-fibre stiffness for structural parts that live outdoors under load.',
    avoidWhenText: 'You don’t have an enclosed, well-ventilated printer with a hardened nozzle — this is one of the most demanding filaments to print well.',
    tags: ['outdoor-safe', 'engineering'],
  },
  {
    id: 'tpu-95a',
    name: 'TPU (95A)',
    chemistry: 'Thermoplastic polyurethane',
    bestFor: 'Phone cases, gaskets, flexible hinges and vibration dampers',
    nozzleTempC: 225,
    bedTempC: 50,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: true,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Intermediate',
    moisture: 'Medium',
    abrasive: false,
    priceZarPerKgLow: 350,
    priceZarPerKgHigh: 550,
    priceEstimated: false,
    whyChooseIt: 'Rubber-like flexibility with real abrasion and impact resistance — genuinely durable, not just bendy.',
    avoidWhenText: 'Your printer has a Bowden setup without careful tuning — TPU jams and grinds in anything but a direct-drive extruder.',
    tags: ['flexible'],
  },
  {
    id: 'tpe',
    name: 'TPE',
    chemistry: 'Thermoplastic elastomer',
    bestFor: 'Very soft-touch grips, seals and wearables needing more stretch than TPU',
    nozzleTempC: 220,
    bedTempC: 40,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: true,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Advanced',
    moisture: 'Medium',
    abrasive: false,
    priceZarPerKgLow: 400,
    priceZarPerKgHigh: 650,
    priceEstimated: true,
    whyChooseIt: 'Softer and stretchier than TPU for grips, seals and wearables that need genuine elasticity.',
    avoidWhenText: 'You need dimensional precision or fast print speeds — very soft TPE is even harder to control than TPU and needs slow, careful printing.',
    tags: ['flexible'],
  },
  {
    id: 'nylon-pa',
    name: 'Nylon (PA)',
    chemistry: 'Polyamide',
    bestFor: 'Gears, living hinges and wear-resistant mechanical parts',
    nozzleTempC: 260,
    bedTempC: 80,
    requiresEnclosure: true,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'High',
    abrasive: false,
    priceZarPerKgLow: 450,
    priceZarPerKgHigh: 650,
    priceEstimated: false,
    whyChooseIt: 'Outstanding toughness, wear resistance and fatigue life — the go-to for gears and mechanical wear parts.',
    avoidWhenText: 'You can’t dry and store it carefully — nylon pulls moisture from the air within hours and prints terribly (bubbling, weak layers) once wet.',
    tags: ['engineering'],
  },
  {
    id: 'pa-cf',
    name: 'PA-CF (Nylon-CF)',
    chemistry: 'Nylon reinforced with chopped carbon fibre',
    bestFor: 'High-load mechanical parts and jigs needing metal-replacement stiffness',
    nozzleTempC: 270,
    bedTempC: 95,
    requiresEnclosure: true,
    requiresHardenedNozzle: true,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'High',
    abrasive: true,
    priceZarPerKgLow: 700,
    priceZarPerKgHigh: 1100,
    priceEstimated: true,
    whyChooseIt: 'Near-metal stiffness-to-weight ratio with excellent fatigue and wear resistance for demanding mechanical parts.',
    avoidWhenText: 'You don’t have a hardened nozzle and a well-dried, enclosed setup — it combines nylon’s moisture sensitivity with carbon fibre’s nozzle wear.',
    tags: ['engineering'],
  },
  {
    id: 'pc',
    name: 'Polycarbonate (PC)',
    chemistry: 'Polycarbonate',
    bestFor: 'High-strength, heat-resistant structural brackets and light housings',
    nozzleTempC: 280,
    bedTempC: 110,
    requiresEnclosure: true,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'High',
    abrasive: false,
    priceZarPerKgLow: 450,
    priceZarPerKgHigh: 650,
    priceEstimated: false,
    whyChooseIt: 'Exceptional impact strength and heat resistance (past 110°C) — genuinely tough, load-bearing parts.',
    avoidWhenText: 'Your printer can’t sustain a hot enclosure and high bed temps — PC warps and delaminates badly on open-frame printers.',
    tags: ['engineering'],
  },
  {
    id: 'pc-abs',
    name: 'PC-ABS',
    chemistry: 'Polycarbonate/ABS blend',
    bestFor: 'Automotive-style parts needing PC’s strength with ABS’s easier printability',
    nozzleTempC: 260,
    bedTempC: 100,
    requiresEnclosure: true,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'Medium',
    abrasive: false,
    priceZarPerKgLow: 450,
    priceZarPerKgHigh: 650,
    priceEstimated: true,
    whyChooseIt: 'Blends PC’s toughness and heat resistance with ABS’s easier, less brittle printing behaviour.',
    avoidWhenText: 'You need pure PC’s maximum heat resistance — the ABS content lowers the ceiling versus straight polycarbonate.',
    tags: ['engineering'],
  },
  {
    id: 'hips',
    name: 'HIPS',
    chemistry: 'High-impact polystyrene',
    bestFor: 'Dissolvable support material for ABS prints, and lightweight low-cost prototypes',
    nozzleTempC: 230,
    bedTempC: 95,
    requiresEnclosure: true,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: false,
    recommendsVentilation: true,
    difficulty: 'Intermediate',
    moisture: 'Low',
    abrasive: false,
    priceZarPerKgLow: 300,
    priceZarPerKgHigh: 450,
    priceEstimated: false,
    whyChooseIt: 'Dissolves cleanly in limonene, making it the standard soluble support material for ABS dual-extrusion prints.',
    avoidWhenText: 'You need a durable end-use part on its own — HIPS is soft compared to ABS and mainly earns its keep as a support material.',
    tags: [],
  },
  {
    id: 'pva',
    name: 'PVA',
    chemistry: 'Polyvinyl alcohol',
    bestFor: 'Water-soluble support material for complex overhangs on PLA/PETG prints',
    nozzleTempC: 200,
    bedTempC: 50,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: true,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Advanced',
    moisture: 'High',
    abrasive: false,
    priceZarPerKgLow: 800,
    priceZarPerKgHigh: 1200,
    priceEstimated: true,
    whyChooseIt: 'Dissolves completely in plain water, letting you print complex overhangs and internal channels cleanly.',
    avoidWhenText: 'Your printer isn’t dual-extrusion or the room is humid — PVA absorbs moisture almost immediately and becomes unusable if left unsealed.',
    tags: [],
  },
  {
    id: 'pvb',
    name: 'PVB',
    chemistry: 'Polyvinyl butyral',
    bestFor: 'Vapour-smoothed display models and figurines wanting a glass-like finish',
    nozzleTempC: 210,
    bedTempC: 55,
    requiresEnclosure: false,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Intermediate',
    moisture: 'Medium',
    abrasive: false,
    priceZarPerKgLow: 400,
    priceZarPerKgHigh: 600,
    priceEstimated: true,
    whyChooseIt: 'Prints like PLA but smooths to an almost glass-clear finish with an isopropyl-alcohol vapour bath.',
    avoidWhenText: 'You need a strong functional part — PVB targets cosmetic display pieces, not load-bearing use.',
    tags: [],
  },
  {
    id: 'pp',
    name: 'Polypropylene (PP)',
    chemistry: 'Polypropylene',
    bestFor: 'Living hinges, snap-fit parts and chemical-resistant containers',
    nozzleTempC: 230,
    bedTempC: 100,
    requiresEnclosure: true,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: false,
    recommendsVentilation: false,
    difficulty: 'Advanced',
    moisture: 'Low',
    abrasive: false,
    priceZarPerKgLow: 400,
    priceZarPerKgHigh: 600,
    priceEstimated: true,
    whyChooseIt: 'Outstanding fatigue resistance for living hinges plus strong resistance to fuels, acids and household chemicals.',
    avoidWhenText: 'Your bed adhesion setup can’t handle it — PP detaches from nearly every standard bed surface without PP-specific adhesive or an enclosure.',
    tags: ['engineering'],
  },
  {
    id: 'pbt',
    name: 'PBT',
    chemistry: 'Polybutylene terephthalate',
    bestFor: 'Engineering parts needing nylon-like toughness with less moisture sensitivity',
    nozzleTempC: 250,
    bedTempC: 90,
    requiresEnclosure: true,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Advanced',
    moisture: 'Medium',
    abrasive: false,
    priceZarPerKgLow: 500,
    priceZarPerKgHigh: 750,
    priceEstimated: true,
    whyChooseIt: 'Nylon-like toughness and fatigue resistance with noticeably less moisture sensitivity and warp.',
    avoidWhenText: 'You need a filament that’s forgiving on an open-frame beginner printer — PBT still wants a controlled, enclosed environment to print reliably.',
    tags: ['engineering'],
  },
  {
    id: 'pbt-gf',
    name: 'PBT-GF',
    chemistry: 'PBT reinforced with glass fibre',
    bestFor: 'High-stiffness mechanical parts needing dimensional stability under load',
    nozzleTempC: 260,
    bedTempC: 95,
    requiresEnclosure: true,
    requiresHardenedNozzle: true,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Advanced',
    moisture: 'Medium',
    abrasive: true,
    priceZarPerKgLow: 650,
    priceZarPerKgHigh: 950,
    priceEstimated: true,
    whyChooseIt: 'Glass fibre adds stiffness and heat resistance over unfilled PBT with minimal extra warp.',
    avoidWhenText: 'You’re printing through a standard brass nozzle — glass fibre wears brass just as fast as carbon fibre and needs a hardened nozzle.',
    tags: ['engineering'],
  },
  {
    id: 'pbt-cf',
    name: 'PBT-CF',
    chemistry: 'PBT reinforced with chopped carbon fibre',
    bestFor: 'Lightweight, stiff structural parts where PBT-GF’s extra weight is a downside',
    nozzleTempC: 260,
    bedTempC: 95,
    requiresEnclosure: true,
    requiresHardenedNozzle: true,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Advanced',
    moisture: 'Medium',
    abrasive: true,
    priceZarPerKgLow: 750,
    priceZarPerKgHigh: 1100,
    priceEstimated: true,
    whyChooseIt: 'Higher stiffness-to-weight ratio than PBT-GF, ideal where every gram matters on a structural part.',
    avoidWhenText: 'Cosmetic appearance matters — like all carbon-fibre composites it prints matte and grainy, and the fibres chew through brass nozzles fast.',
    tags: ['engineering'],
  },
  {
    id: 'pc-pbt',
    name: 'PC-PBT',
    chemistry: 'Polycarbonate/PBT blend',
    bestFor: 'Automotive and connector-housing parts needing impact plus chemical resistance',
    nozzleTempC: 270,
    bedTempC: 100,
    requiresEnclosure: true,
    requiresHardenedNozzle: false,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'Medium',
    abrasive: false,
    priceZarPerKgLow: 600,
    priceZarPerKgHigh: 900,
    priceEstimated: true,
    whyChooseIt: 'Combines PC’s impact toughness with PBT’s chemical and fatigue resistance — aimed at connector and automotive-style housings.',
    avoidWhenText: 'You don’t have a genuinely enclosed, high-temperature-capable printer — this blend needs the same demanding setup as straight PC.',
    tags: ['engineering'],
  },
  {
    id: 'pet-cf',
    name: 'PET-CF',
    chemistry: 'PET reinforced with chopped carbon fibre',
    bestFor: 'Stiff, dimensionally stable mechanical parts wanting PETG-like ease with more rigidity',
    nozzleTempC: 270,
    bedTempC: 85,
    requiresEnclosure: false,
    requiresHardenedNozzle: true,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: false,
    difficulty: 'Intermediate',
    moisture: 'Medium',
    abrasive: true,
    priceZarPerKgLow: 550,
    priceZarPerKgHigh: 800,
    priceEstimated: true,
    whyChooseIt: 'PET’s chemical resistance and stability with carbon fibre’s added stiffness, and less stringing than PETG-CF.',
    avoidWhenText: 'You need a cosmetic finish or you’re printing with a standard brass nozzle — carbon fibre leaves a matte texture and needs a hardened nozzle.',
    tags: ['engineering'],
  },
  {
    id: 'pps-cf',
    name: 'PPS-CF',
    chemistry: 'Polyphenylene sulfide reinforced with chopped carbon fibre',
    bestFor: 'Extreme-temperature, chemically aggressive industrial environments (under-hood automotive, aerospace)',
    nozzleTempC: 330,
    bedTempC: 140,
    requiresEnclosure: true,
    requiresHardenedNozzle: true,
    requiresDirectDrive: false,
    recommendsDryFilament: true,
    recommendsVentilation: true,
    difficulty: 'Advanced',
    moisture: 'Medium',
    abrasive: true,
    priceZarPerKgLow: 4000,
    priceZarPerKgHigh: 7000,
    priceEstimated: true,
    whyChooseIt: 'Exceptional chemical and heat resistance (continuous use well past 200°C) with carbon-fibre stiffness, for genuinely industrial applications.',
    avoidWhenText: 'You don’t have a high-temperature industrial printer — PPS-CF needs processing temperatures and an all-metal hotend far beyond desktop FDM machines.',
    tags: ['engineering', 'outdoor-safe'],
  },
];

async function main() {
  for (const plan of PLANS) {
    const existing = await prisma.plan.findFirst({ where: { name: plan.name } });
    if (!existing) {
      // Create-only: a manual price edit in the DB (the intended way to
      // change pricing until the admin center exists — see the design
      // spec) must survive a re-run of this seed script. Only sortOrder
      // and active-flag drift would ever need re-syncing here, and
      // neither of those exists yet, so a bare create-if-missing is
      // correct — revisit if this script ever needs to reconcile more
      // than existence.
      await prisma.plan.create({ data: plan });
    }
  }

  for (const material of MATERIALS) {
    await prisma.material.upsert({
      where: { id: material.id },
      create: material,
      update: material,
    });
  }
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
